### ISSUE TITLE
Set up CI in node-valut-fork

### ISSUE THREAD

**Issue by eheikes** [Banno/node-vault-fork#8]
I think we should either get the TravisCI config working, or set up a Jenkins pipeline to run tests etc for PRs.

**Comment by brandonros** [comment]
Does my comment https://github.com/Banno/node-vault-fork/pull/7#issuecomment-463704217 here change the way you view this at all? In my eyes, to pour effort into something we really didn't want to fork in the first place kind of stinks. :(

**Comment by eheikes** [comment]
Since the original repo already has tests and a TravisCI config, I was hoping that it wouldn't take much time to get up & running. The TravisCI builds are already running even: https://travis-ci.com/Banno/node-vault-fork/. But I agree that this would be a low priority, though our services lean pretty heavy on it.

Unfortunately, creating a fork means that we are now responsible for maintaining the fork. That's why it's usually a last resort after creating a PR against the original repo and such.

**Comment by bjork24** [comment]
Tracking in [NODE-67]

[NODE-67]: https://banno-jha.atlassian.net/browse/NODE-67
