### ISSUE TITLE
Get this merged into kr1sp1n's package

### ISSUE THREAD

**Issue by brandonros** [Banno/node-vault-fork#9]
Try to get kr1sp1n to merge our changes (transit support and Postgres credentials)

**Comment by brandonros** [comment]
Thoughts and prayers that we get this merged: https://github.com/kr1sp1n/node-vault/pull/115/files

**Comment by brandonros** [comment]
https://github.com/kr1sp1n/node-vault/pull/115 was made with clear documentation of intent on what we want to do, not 500 commits that need squashing, and a passing build. I can not find kr1sp1n (Krispin Schulz)'s e-mail online to personally e-mail him.

**Comment by eheikes** [comment]
Have we tried messaging through Twitter or LinkedIn yet? 

* https://twitter.com/kr1sp1n
* https://www.linkedin.com/in/krispin-schulz-59606820/

**Comment by brandonros** [comment]
LinkedIn: sent him a connection request with a note.

Twitter: can you do this one?

**Comment by eheikes** [comment]
Emails from npm pkg:

* `krispin@posteo.de` (https://github.com/kr1sp1n/node-vault/blob/master/package.json#L57)
* `krispinone@gmail.com` (`npm owner ls node-vault`)

Tried these yet?

**Comment by eheikes** [comment]
Here's the official process for transferring ownership: https://www.npmjs.com/policies/disputes
cc NPM

**Comment by bjork24** [comment]
[NODE-191]

[NODE-191]: https://banno-jha.atlassian.net/browse/NODE-191
